StudioReservation.BackOffice/Controllers/TimeSlotController.cs
using StudioReservation.BackOffice.Models;
using StudioReservation.Contract;
using StudioReservation.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;

namespace StudioReservation.BackOffice.Controllers
{
    public class TimeSlotController : Controller
    {
        public IReservationService _reservationService;

        public TimeSlotController()
        {
            _reservationService = ServiceConnection._reservationService;
        }        
        public ActionResult Index()
        {
            var result = _reservationService.FindAllRoomTimeSlot();
            if (result.Error != 0)
            {
                ViewBag.ErrorCode = result.Error.ToString();
                return View("Error");
            }
            return View(result);
        }
        //public ActionResult Index1()
        //{
        //    ViewBag.RoomId = "";
        //    ViewBag.StartDate = "";
        //    ViewBag.EndDateDate = "";
        //    var result = _reservationService.FindAllRoomTimeSlot();
        //    //if (result.Error != 0)
        //    //{
        //    //    ViewBag.ErrorCode = result.Error.ToString();
        //    //    return View("Error");
        //    //}
        //    List<string> roomList = new List<string>() { "Studio1", "Studio2"};
        //    ViewBag.MovieShow = new SelectList(roomList);

        //    return View(result);
        //}

        public ActionResult CreateGet(int roomId = 0)
        {
            CreateTimeSlotRequest model = new CreateTimeSlotRequest();

            var result = _reservationService.GetNotAvailableRoomDate(roomId);
            ViewBag.DisabledDate = result.NotAvailableDates;
            ViewBag.StartDate = result.StartTime;
            ViewBag.EndDate = result.EndTime;

            List<SelectListItem> roomList = new List<SelectListItem>();
            foreach(var i in result.Room)
            {
                roomList.Add(new SelectListItem()
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
            }

            List<SelectListItem> timeslots = new List<SelectListItem>()
                {
                    new SelectListItem(){ Text = "00:00", Value = "00:00"},
                    new SelectListItem(){ Text = "01:00", Value = "01:00"},
                    new SelectListItem(){ Text = "02:00", Value = "02:00"},
                    new SelectListItem(){ Text = "03:00", Value = "03:00"},
                    new SelectListItem(){ Text = "04:00", Value = "04:00"},
                    new SelectListItem(){ Text = "05:00", Value = "05:00"},
                    new SelectListItem(){ Text = "06:00", Value = "06:00"},
                    new SelectListItem(){ Text = "07:00", Value = "07:00"},
                    new SelectListItem(){ Text = "08:00", Value = "08:00"},
                    new SelectListItem(){ Text = "09:00", Value = "09:00"},

                    new SelectListItem(){ Text = "10:00", Value = "10:00"},
                    new SelectListItem(){ Text = "11:00", Value = "11:00"},
                    new SelectListItem(){ Text = "12:00", Value = "12:00"},
                    new SelectListItem(){ Text = "13:00", Value = "13:00"},
                    new SelectListItem(){ Text = "14:00", Value = "14:00"},
                    new SelectListItem(){ Text = "15:00", Value = "15:00"},
                    new SelectListItem(){ Text = "16:00", Value = "16:00"},
                    new SelectListItem(){ Text = "17:00", Value = "17:00"},
                    new SelectListItem(){ Text = "18:00", Value = "18:00"},
                    new SelectListItem(){ Text = "19:00", Value = "19:00"},

                    new SelectListItem(){ Text = "20:00", Value = "20:00"},
                    new SelectListItem(){ Text = "21:00", Value = "21:00"},
                    new SelectListItem(){ Text = "22:00", Value = "22:00"},
                    new SelectListItem(){ Text = "23:00", Value = "23:00"}
                };
            ViewBag.Timeslots = new MultiSelectList(timeslots, "Value", "Text");

            if (roomId == 0)
            {                 
                ViewBag.RoomId = new SelectList(roomList, "Value", "Text");               
            }
            else
            {
                roomList.Where(x => x.Value ==  roomId.ToString()).First().Selected = true;
                ViewBag.RoomId = new SelectList(roomList, "Value", "Text");
            }
            return View(model);
        }
        [HttpPost]
        //public ActionResult Create([Bind(Include = "RoomId,Times,Enable,Dates")] CreateTimeSlotRequest request)
        public ActionResult Create(CreateTimeSlotRequest request)
        {
            if(request.Times == null )
            {
                ViewBag.errorMessage = "Please select at least one timeslot.";
                return View("Error");
            }
            
            var data = new CreateRoomTimeSlot
            {
                RoomId = request.RoomId,
                Dates = request.Dates,
                Times = request.Times,
                Enable = request.Enable,
                CreatedBy = "",
                CreateTime = DateTime.Now,
                UpdateBy = "",
                UpdateTime = DateTime.Now,
            };

            var result = _reservationService.CreateTimeSlot(data);
            if(result != 0)
            {
                ViewBag.ErrorCode = result.ToString();
                return View("Error");
            }

            return RedirectToAction("Index"); // 0 is success , other code is fail
        }
        [HttpGet]
        public ActionResult EditGet(long recordId)
        {
            var result = _reservationService.FindDetail(recordId);

            if(result.Error != 0)
            {
                ViewBag.ErrorCode = result.Error.ToString();
                return View("Error");
            }
            if (result.EnableEdit == false)
            {
                ViewBag.errorMessage = "You are not allowed to edit today or passed time slot.";
            }
            EditTimeSlot model = new EditTimeSlot()
            {
                Id= result.Id,
                RoomName = result.RoomName,
                Enable = result.Enable,
                Date = result.Date,
                TimeDic=result.Times,
            };

            return View(model); 
        }

        [HttpPost]
        public ActionResult Edit(EditTimeSlot request)
        {
            List<String> avaiAndReserveSlots = new List<string>();
            if (request.Times != null)
                avaiAndReserveSlots.AddRange(request.Times);
            if(request.DisabledTimes!= null)
                avaiAndReserveSlots.AddRange(request.DisabledTimes.Split(','));
            avaiAndReserveSlots.Sort();

            if (avaiAndReserveSlots.Count() == 0)
            {
                ViewBag.errorMessage = "Please select at least one timeslot.";
                return View("Error");
            }
            var result = _reservationService.EditTimeSlot(request.Id, string.Join(",", avaiAndReserveSlots), string.Empty, DateTime.Now, request.Enable);
            if (result != 0)
            {
                ViewBag.ErrorCode = result.ToString();
                return View("Error");
            }

            return RedirectToAction("Index");
        }

        public ActionResult ConfirmDelete(string recordId = "")
        {
            var result = _reservationService.DeleteTimeSlot(long.Parse(recordId));

            if (result != 0)
            {
                ViewBag.ErrorCode = result.ToString();
                return View("Error");
            }

            return RedirectToAction("Index"); // 0 is success , other code is fail
        }

        //[HttpGet]
        //public ActionResult GetAll()
        //{

        //    var result = _reservationService.FindAllRoomTimeSlot();

        //    if (result.Error != 0)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(result);
        //}

        //[HttpGet]
        //public ActionResult Search(int roomId, DateTime startTime, DateTime endTime)
        //{

        //    var result = _reservationService.FindRoomTimeSlotByFilter(roomId, startTime, endTime);

        //    if (result.Error != 0)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(result);
        //}

        //[HttpGet]
        //public ActionResult FindDetail(long Id)
        //{

        //    var result = _reservationService.FindDetail(Id);

        //    if (result.Error != 0)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(result);
        //}

        //[HttpGet]
        //public ActionResult FindNotAvailableDate(int roomId)
        //{
        //    var result = _reservationService.GetNotAvailableRoomDate(roomId);

        //    return View(result);
        //}
    }
}

StudioReservation.BackOffice/Views/TimeSlot/CreateGet.cshtml
@model StudioReservation.BackOffice.Models.CreateTimeSlotRequest
@{
    ViewBag.Title = "Create New Timeslot";
}
<link href="~/Content/Chosen/chosen.min.css" rel="stylesheet" />

<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <br />
    @using (Html.BeginForm("Create", "TimeSlot", FormMethod.Post, new { role = "form" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" id="DisabledDate" value="@ViewBag.DisabledDate" />
        <input type="hidden" id="StartDate" value="@ViewBag.StartDate" />
        <input type="hidden" id="EndDate" value="@ViewBag.EndDate" />
        <div class="row">
            @Html.LabelFor(m => m.RoomId, new { @class = "col-md-8 col-form-label" })
            <div class="col-md-8">
                @Html.DropDownListFor(m => m.RoomId, ViewBag.RoomId as SelectList, "--Select Room--", new { @class = "form-control", id = "RoomId", name = "RoomId" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(m => m.Dates, new { @class = "col-md-8 col-form-label" })
            <div class="col-md-8">
                <div class="input-group date">
                    <input type="text" class="form-control" id="Dates" name="Dates" value="@Model.Dates">
                    <span class="input-group-append">
                        <span class="input-group-text bg-white d-block">
                            <i class="fa-regular fa-calendar-days"></i>
                        </span>
                    </span>
                </div>
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(m => m.Enable, new { @class = "col-md-8 col-form-label" })
            <div class="col-md-8" style="margin-top:8px;">
                <input type="radio" name="radiobutton" class="rd" value="true" />Yes
                <input type="radio" name="radiobutton" class="rd" value="false" />No
                @Html.HiddenFor(m => m.Enable)
            </div>
        </div>

        <div class="row">
            @Html.Label("Times", new { @class = "col-md-8 col-form-label" })
            <div class="col-md-8">
                @Html.ListBoxFor(m => m.Times, ViewBag.Timeslots as MultiSelectList, new { id = "Times", multiple = "multiple" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="offset-md-3 col-md-9">
                <input type="submit" value="Create" class="btn btn-primary" id="submitBtn" />
            </div>
        </div>
    }
</main>

@section scripts
{
    <script src="~/Scripts/chosen.jquery.min.js"></script>
    <script src="~/Scripts/init.js"></script>
    @Scripts.Render("~/bundles/datepicker")
<script type="text/javascript">
        $(document).ready(function () {

            if ($('#RoomId').val() == '') {
                $('#Dates').prop('disabled', true);
                $('.rd').prop('disabled', true);
                $('#Times').prop('disabled', true);
                $('#submitBtn').prop('disabled', true);
            };
            let disabledDate = $('#DisabledDate').val().split(',');
            $('.input-group').datepicker({
                format: "dd/mm/yyyy",
                weekStart: 1,
                todayBtn: "linked",
                multidate: true,
                orientation: "bottom left",
                startDate: $('#StartDate').val(),
                endDate: $('#EndDate').val(),
                datesDisabled: disabledDate,

            });

            $("#Times").chosen({ width: "50%" });

            $('.rd').click(function () {
                document.getElementById("Enable").value = $('input[name ="radiobutton"]:checked').val();
                //alert(document.getElementById("Enable").value);
            });

            $('#RoomId').change(function () {
                window.location.href = '@Html.Raw(@Url.Action("CreateGet", "TimeSlot"))' + '?roomId=' + this.value;
            });
        });
</script>
}

StudioReservation.BackOffice/Views/TimeSlot/EditGet.cshtml
@model StudioReservation.BackOffice.Models.EditTimeSlot
@{
    ViewBag.Title = "Editing Timeslot";
}

<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <br />
    @using (Html.BeginForm("Edit", "TimeSlot", FormMethod.Post, new { role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.RoomName)
        @Html.HiddenFor(m => m.Date)
        @Html.HiddenFor(m => m.DisabledTimes)

        <div class="row">
            @Html.LabelFor(m => m.RoomName, new { @class = "col-md-8 col-form-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.RoomName, new { @class = "form-control", disabled = "disabled" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(m => m.Date, new { @class = "col-md-8 col-form-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.Date, new { @class = "form-control", disabled = "disabled" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(m => m.Enable, new { @class = "col-md-8 col-form-label" })
            <div class="col-md-8" style="margin-top:8px;">
                @Html.RadioButtonFor(m => m.Enable, "True") Yes
                @Html.RadioButtonFor(m => m.Enable, "False") No
            </div>
        </div>

        <div class="row">

            <div class="col-md-7">
                @Html.LabelFor(m => m.Times, new { @class = "col-md-12 col-form-label" })
                @for (int i = 0; i < 24; i++)
                {
                    int v;
                    string val = i.ToString("D2") + ":00";
                    if (Model.TimeDic.TryGetValue(val, out v) && (v == 2 || v == 3))
                    {
                        <input type="checkbox" id="Times" name="Times" value="@val" disabled checked /><label>@val<span>&nbsp;</span></label>
                    }
                    else if ((Model.TimeDic.TryGetValue(val, out v) && v == 1))
                    {
                        <input type="checkbox" id="Times" name="Times" value="@val" checked /><label>@val<span>&nbsp;</span></label>
                    }
                    else
                    {
                        <input type="checkbox" id="Times" name="Times" value="@val" /><label>@val<span>&nbsp;</span></label>
                    }
                }
                <br />
            </div>

            @*<div class="col-md-3 col-sm-3" style="border:2px groove lime">
                        <h6>&lowast; Reserved</h6>
                        @foreach (var item in Model.TimeDic)
                        {
                            if (item.Value == 2 || item.Value == 3)
                            {
                                <input type="checkbox" name="DisTimes" value="@item.Key" disabled checked/><label style="text-decoration: line-through">@item.Key<span>&nbsp;</span></label>
                            }
                        }
                </div>*@
        </div>
        <br />
        <div class="row">
            <div class="offset-md-3 col-md-9">
                <input type="submit" value="Update" class="btn btn-primary" id="submitBtn" onclick="PostingDisTimes()" />
            </div>
        </div>
    }
</main>

@section scripts
{
    <script type="text/javascript">
        var disTimes = [];
        function PostingDisTimes() {
            
            $('input[name ="Times"]:disabled').each(function () {
                disTimes.push(this.value);
            });
            $('#DisabledTimes').val(disTimes);

        }
    </script>
}

StudioReservation.BackOffice/Views/TimeSlot/Index.cshtml
@model StudioReservation.DataModel.ViewAllTimeSlot
@{
    ViewBag.Title = "Time Slot Management";
}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.1.2/css/dataTables.dataTables.css" />
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>

    <input type="button" class="btn btn-primary" value="Create New" onclick="CreateNew()" />
    <br />
    <div class="row table-responsive">
        <table class="table table-bordered" id="TimeslotView">
            <thead class="table-secondary">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Room</th>
                    <th scope="col">Date</th>
                    <th scope="col">Registered slots</th>
                    <th scope="col">Booked slots</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.TimeSlots)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.RoomName</td>
                        <td>@item.Date</td>
                        <td>@item.AvailableTime</td>
                        <td>@item.BookedTime</td>
                        <td>
                            @Html.ActionLink("Edit", "EditGet", new { recordId = item.Id }, new { style = "text-decoration:none;" })
                            @if (item.AbleToDelete)
                            {
                                <span>|</span> //@Html.ActionLink("Remove", "Remove", new { id = item.Id }, new {id = "RemoveTimeSlotBtn"})
                                <btn id="@item.Id" style="color:#0d6efd" onclick="PopConfirm(this)">Remove</btn>
                            }
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</main>
<!-- Modal -->
<div class="modal fade modal-sm" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Confirmation <i class="fa-solid fa-exclamation"></i></h5>
            </div>
            <div class="modal-body">
                Do you confirm to remove this record? ID:<input type="Text" id="roomIdToRemove" style="width:100px;" disabled/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" onclick="ConfirmDelete()">Yes</button>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script src="https://cdn.datatables.net/2.1.2/js/dataTables.js"></script>
    <script type="text/javascript">
        

        function ConfirmDelete() {
            window.location.href = '@Html.Raw(@Url.Action("ConfirmDelete", "TimeSlot"))' + "?recordId=" + $('#roomIdToRemove').val();
        }

        function CreateNew() {
            window.location.href = '@Html.Raw(@Url.Action("CreateGet", "TimeSlot"))';
        }

        function PopConfirm(e) {
            $('#roomIdToRemove').val(e.id);
            $('#staticBackdrop').modal('show');
        }

        $(document).ready(function () {
            $('#TimeslotView').DataTable({
                order: [[0, 'asc']]
            });
        });

    </script>
}

StudioReservation.BackOffice/Views/TimeSlot/Index1.cshtml
@model StudioReservation.DataModel.ViewAllTimeSlot
@{
    ViewBag.Title = "Time Slot Management";
}

<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>

    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-8" style="background-color:lightblue; border-radius:15px;">
            <div class="col-md-12 col-sm-12" style="margin-left: 15px;">
                <b>Filter</b>
            </div>

            <div class="col-md-6 col-sm-6">
                @Html.LabelFor(m => m.TimeSlots[0].RoomId, new { @class = "col-md-3" })
                @Html.DropDownListFor(model => model.TimeSlots[0].RoomId, ViewBag.MovieShow as SelectList, new { @class = "col-md-5" })
            </div><br />

                  <div class="col-md-12 col-sm-12">
                      <label class="col-md-2">Start Date</label>
                      <div class="col-md-3" style="display:inline-block">
                          <div class="input-group date">
                              <input type="text" class="form-control" id="startDateFilter" value="">
                              <span class="input-group-append">
                                  <span class="input-group-text bg-white d-block">
                                      <i class="fa-regular fa-calendar-days"></i>
                                  </span>
                              </span>
                          </div>
                      </div>


                      @*<input type="Text" id="startDateFilter" class="col-md-3" />*@
                      <label class="col-md-2">End Date</label>
                      <div class="col-md-3" style="display:inline-block">
                          <div class="input-group date">
                              <input type="text" class="form-control" id="endDateFilter" value="">
                              <span class="input-group-append">
                                  <span class="input-group-text bg-white d-block">
                                      <i class="fa-regular fa-calendar-days"></i>
                                  </span>
                              </span>
                          </div>
                      </div>
                      @*<input type="Text" id="endDateFilter" class="col-md-3" />*@
                  </div>
                  <br/>
                  <div class="row">
                      <div class="col-md-2 offset-md-5">
                          <input type="button" class="btn btn-sm btn-primary" value="Search" />
                      </div>
                      
                  </div>            

                 
        </div>
    </div>


</main>